Bitbucket: {
  shape: image
  icon: https://icons.terrastruct.com/dev%2Fbitbucket.svg
}

Infrastructure {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F245-folder.svg
}

*.json files {
  templates\.master\.json {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F257-file.svg
  }
  templates\.platform\.json {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F257-file.svg
  }
  templates\.billing\.json {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F257-file.svg
  }
  templates\.client\.json {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F257-file.svg
  }
  templates\.json {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F257-file.svg
  }
}

servo-script-templates {
  shape: image
  icon: https://icons.terrastruct.com/aws%2FStorage%2FAmazon-Simple-Storage-Service-S3_Bucket_light-bg.svg
}


Terraform

Servo 

# Arrows / Directions

Bitbucket -> Infrastructure
Infrastructure -> *.json files
*.json files -> Terraform: refactor json files
Terraform -> servo-script-templates: terraform detects changes and modifies existing files in s3 bucket

servo-script-templates -> Servo: servo reads from the bucket

